# Generated by Django 6.0.3 on 2026-03-19 17:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_title', models.CharField(max_length=500)),
                ('application_name', models.CharField(max_length=255)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'desktop_activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
