# Generated by Django 6.0.3 on 2026-03-23 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_desktopactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='shift_end_time',
            field=models.TimeField(default=datetime.time(17, 30), help_text='Time after which ongoing attendance automatically drops the calculating status'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='shift_start_time',
            field=models.TimeField(default=datetime.time(9, 30), help_text='Official shift starting time'),
        ),
        migrations.DeleteModel(
            name='DesktopActivityLog',
        ),
    ]
