# Generated by Django 6.0.3 on 2026-03-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_attendancepolicy_shift_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='session_timeout_hours',
            field=models.PositiveIntegerField(default=24, help_text='Maximum duration in hours for a single login session before auto-logout'),
        ),
    ]
