# Generated by Django 6.0.3 on 2026-03-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_attendancepolicy_session_timeout_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='present_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Minimum hours to mark attendance as Present', max_digits=4),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='min_working_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Minimum hours for Full Day status', max_digits=4),
        ),
    ]
