# Generated by Django 6.0.3 on 2026-04-02 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_is_online_user_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='screenshots/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_captures', to=settings.AUTH_USER_MODEL)),
                ('work_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_captures', to='core.worksession')),
            ],
            options={
                'db_table': 'screen_captures',
                'ordering': ['-timestamp'],
            },
        ),
    ]
