# Generated by Django 6.0.3 on 2026-06-15 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_screencapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.shift'),
        ),
    ]
