# Generated by Django 6.0.3 on 2026-06-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='base_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Base hourly wage rate for employees on this policy', max_digits=10),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='night_differential_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.2, help_text='Differential multiplier for hours worked during night shift (e.g. 1.20)', max_digits=4),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='overtime_rate_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Overtime multiplier (e.g. 1.50 for time and a half)', max_digits=4),
        ),
    ]
