# Generated by Django 6.0.3 on 2026-07-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_attendancepolicy_base_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaksession',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='idlelog',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
