# Generated by Django 6.0.3 on 2026-07-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_breaksession_end_time_alter_idlelog_end_time_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='breaksession',
            index=models.Index(fields=['work_session', 'start_time'], name='break_sessi_work_se_7db862_idx'),
        ),
        migrations.AddIndex(
            model_name='idlelog',
            index=models.Index(fields=['work_session', 'start_time'], name='idle_logs_work_se_1e0df3_idx'),
        ),
    ]
